[project]
name = "mitchie-tic-tac-toe"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.1",
    "numpy>=2.2.3",
    "vpython>=7.6.5",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
